name: 'Server Chan'
description: 'Use serverchan in github action'
author: Mioto <yaku.mioto@gmail.com>
branding:
  icon: 'alert-octagon'
  color: 'gray-dark'
inputs:
  key:
    description: Secret key
    required: true
  text:
    description: Message title
    required: true
  desp:
    description: Message content
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.key }}
    - ${{ inputs.text }}
    - ${{ inputs.desp }}