name: 'ServerChan Notify'
description: 'Use server chan in github action'
author: Mioto <yaku.mioto@gmail.com>
branding:
  icon: 'message-circle'
  color: 'blue'
inputs:
  key:
    description: Secret key
    required: true
  title:
    description: Message title
    required: true
  desp:
    description: Message content
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.key }}
    - ${{ inputs.title }}
    - ${{ inputs.desp }}