---
name: serverchan-action

on: [push]

jobs:
  build:
    name: Build
    run-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
      - uses: actions/checkout@v2
      - run: go build -v .